name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build React app
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
      - name: Deploy to GitHub Pages
        uses: actions/download-artifact@v2
        with:
          name: build
        run: |
          mkdir -p public
          cp -r build/* public/
          git add public
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages
